name: heapsort
version: 0.1.0.0
description: Benchmark de estruturas de dados em Haskell
author: Seu Nome
maintainer: seu@email.com
license: BSD-3-Clause

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - vector
    - time
    - random

executables:
  heapsort-exe:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - heapsort